### ISSUE TITLE
Erros de versionamento entre ASP.NET 3.0 e ASP.NET 5.0

### ISSUE THREAD

**Issue by thiagoquinaia** [gabrielfbarros/csharp-examples#3]
Bom dia Professor, 
Sou aluno do BOOTCAMP MRV da DIO. 

Estou assintindo suas aulas agora e me deparei com esse repositório sobre alguns exemplos, porém, estou usando um SDK mais recente que o que vc usou. Estou usando o ASP.NET 5.0, e não consigo simplesmente clonar seu repositório e executar. 

O que posso fazer para converter essas versões?

Desde já agradeço,

**Comment by thiagoquinaia** [comment]
Bom, descobri como realizar essa conversão e gostaria de postar aqui. 
Espero que ajude outros com a mesma dúvida. 

**Primeiro** é necessário alterar o TargetFramework do arquivo .csproj

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
-    <TargetFramework>netcoreapp3.1</TargetFramework>
**+    <TargetFramework>net5.0</TargetFramework>**
  </PropertyGroup>

</Project>
```

**Segundo,** foi necessário alterar o arquivo launch.json, a linha 13 item "program:" onde estava estava definido ...Debug/netcoreapp3.0/E... então troquei para Debug/net5.0/E... 

e executei o programa e deu certo!

Obrigado.

**Comment by gabrielfaraday** [comment]
Valeu @thiagoquinaia
